# Generated by Django 5.1 on 2024-10-02 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ref_id', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('manufacture', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=250)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('review_summary', models.CharField(blank=True, max_length=250, null=True)),
                ('do_recommend_count', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, default='fallback.png', null=True, upload_to='photo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('review_date_added', models.DateField()),
                ('did_purchase', models.BooleanField()),
                ('do_recommend', models.BooleanField()),
                ('review_id', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('source_url', models.URLField()),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
            ],
        ),
    ]
