# Generated by Django 5.1 on 2024-10-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ref_id',
            field=models.CharField(max_length=50),
        ),
    ]
