# Generated by Django 5.1.1 on 2024-10-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='source_url',
        ),
    ]
