# Generated by Django 5.1.1 on 2024-11-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_review_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='five_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='four_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='one_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='three_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='two_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
