# Generated by Django 5.1.1 on 2024-11-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_five_star_count_product_four_star_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highest_sentiment_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
