# Generated by Django 5.1.1 on 2024-11-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_five_star_count_product_four_star_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacture',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='ref_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(),
        ),
    ]
