# Generated by Django 5.1.1 on 2024-11-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_brand_alter_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
