# Generated by Django 5.1.1 on 2024-11-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_review_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highest_sentiment_percentage',
            field=models.CharField(default='Neutral', max_length=100),
            preserve_default=False,
        ),
    ]
